name: mca_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.5
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  flutter_native_splash: ^2.3.6
  connectivity_plus: ^6.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  geocoding: ^3.0.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  flutter_image_compress: ^2.3.0
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^11.0.0
  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  # flutter_launcher_icons: "^0.13.1"
flutter_native_splash:

  color: "#202046" 
  image: assets/images/logo1.png
  fullscreen: true
  android_12:
    image: assets/images/logo1.png 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#202046"
    theme_color: "#202046"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 10 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/dummy_images/
    - assets/images/categories/
    - assets/images/featured_items/
    - assets/images/top_rated_shops/
    - assets/images/more_products/
    - assets/images/popular_shops/
    - assets/images/sale_offers/
    - assets/images/trending_now/
    - assets/images/top_picks/
    - assets/images/products_may_like/
    - assets/images/
    - assets/lottie/
    - assets/.env


  
